# Generated by Django 6.0.7 on 2026-08-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(default=1, upload_to='static'),
            preserve_default=False,
        ),
    ]
