# Generated by Django 6.0.7 on 2026-08-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_author_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
